- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - ssh
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto
  - name: Print the package facts
    ansible.builtin.debug:
      var: ansible_facts.packages
