- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - ssh
      - openssh-server
      - curl
  - ufw:
    rule: allow
    name: OpenSSH
  - ufw:
    rule: allow
    name: http, https
