- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/getname.yml
    - include: tasks/packages.yml
    - include: tasks/execshell.yml
    - include: tasks/users.yml