- hosts: localhost
  gather_facts: yes
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]
become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - ssh
      - openssh-server
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: ssh
