- hosts: localhost
  gather_facts: yes
  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address
become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - ssh
      - openssh-server
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: ssh
