- hosts: localhost
  gather_facts: yes
  
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - ssh
      - openssh-server
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: ssh
