---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: don
        state: present
        key: "{{ lookup('file', '/home/don/.ssh/id_rsa.pub') }}"
  tasks:
    - include: tasks/packages.yml
    