---
- name: Ensure group "ansible" exists
  ansible.builtin.group:
    name: ansible
    state: present

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    recurse: yes
    owner: don
    group: ansible