- name: Install packages
  apt: name={{item}}
  with_items:
    - curl
    - wget
    - git
    - ssh
    - tree
    - openssh-server
    - open-vm-tools
    - unrar
    - zip 
    - unzip 
    - p7zip-full 
    - p7zip-rar 
    - rar